version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safebus-web
    ports:
      - "5070:5050"
    restart: always
    environment:
      - PORT=5050

  api:
    build:
      context: ./EduBus.Api
      dockerfile: Dockerfile
    container_name: safebus-api
    ports:
      - "5071:8080"
    restart: always
